import { AnalysisResult, Template, HistoryItem } from "./types";

export const mockAnalysisResult: AnalysisResult = {
  shots: [
    {
      id: 1,
      timeRange: "0-3s",
      description: "一位穿白衬衫的亚洲女性站在厨房中景，手拿不锈钢锅铲翻炒食材",
      script: "你还在这样炒菜吗？",
      camera: "中景→近景推进",
      mood: "焦虑",
      keyframe: "kitchen_frame_1.jpg",
    },
    {
      id: 2,
      timeRange: "3-9s",
      description: "女性翻开锅盖，蒸汽升起，露出金黄色炒蛋",
      script: "其实只需3步，比饭店还香",
      camera: "近景固定→微推",
      mood: "好奇",
      keyframe: "kitchen_frame_2.jpg",
    },
    {
      id: 3,
      timeRange: "9-18s",
      description: "女性微笑展示成品，桌面摆盘，背景暖色调",
      script: "第一步热油，第二步翻炒，第三步调味",
      camera: "中景→特写切换",
      mood: "释然",
      keyframe: "kitchen_frame_3.jpg",
    },
    {
      id: 4,
      timeRange: "18-27s",
      description: "成品端上桌，家人伸手夹菜，满足表情",
      script: "今晚就试试，评论区告诉我结果",
      camera: "全景→近景",
      mood: "行动欲",
      keyframe: "kitchen_frame_4.jpg",
    },
  ],
  hooks: [
    { type: "提问型", text: "你还在这样炒菜吗？ — 第0秒", position: "0s", score: 8.5 },
    { type: "数字型", text: "只需3步 — 第3秒", position: "3s", score: 7.2 },
    { type: "号召型", text: "今晚就试试 — 第18秒", position: "18s", score: 6.8 },
  ],
  structure: {
    opening: "问题型",
    middle: "步骤型",
    ending: "号召行动",
  },
  emotionCurve: [
    { emotion: "焦虑", color: "#fecaca" },
    { emotion: "好奇", color: "#bfdbfe" },
    { emotion: "释然", color: "#99f6e4" },
    { emotion: "行动", color: "#fde68a" },
  ],
  prompts: [
    {
      shotId: 1,
      timeRange: "0-3s",
      mood: "焦虑",
      sceneType: "美食类",
      textPrompt: "一位穿白衬衫的亚洲年轻女性站在厨房中景，双手拿着不锈钢锅铲翻炒锅中食材，表情焦虑，暖色调侧光，烟火光影质感",
      imagePrompt: "女性手拿锅铲翻炒食材，中景缓慢推进至近景，焦虑表情，暖色调侧光",
      keyframe: "kitchen_frame_1.jpg",
    },
    {
      shotId: 2,
      timeRange: "3-9s",
      mood: "好奇",
      sceneType: "美食类",
      textPrompt: "亚洲女性双手翻开不锈钢锅盖，大量蒸汽从锅中升起，露出金黄色炒蛋，好奇表情，暖色调厨房灯光",
      imagePrompt: "女性翻开锅盖蒸汽升起，近景微推，好奇表情，暖色调灯光",
      keyframe: "kitchen_frame_2.jpg",
    },
    {
      shotId: 3,
      timeRange: "9-18s",
      mood: "释然",
      sceneType: "美食类",
      textPrompt: "亚洲女性微笑展示盘中成品炒蛋，桌面精致摆盘，背景暖色调厨房，中景切换至特写",
      imagePrompt: "女性微笑展示成品，中景至特写切换，释然表情，暖色调厨房",
      keyframe: "kitchen_frame_3.jpg",
    },
    {
      shotId: 4,
      timeRange: "18-27s",
      mood: "行动欲",
      sceneType: "美食类",
      textPrompt: "盘中金黄色炒蛋端上餐桌，家人伸手夹菜露出满足表情，全景至近景，暖色调餐厅灯光",
      imagePrompt: "成品端上桌家人夹菜，全景至近景，满足表情，暖色调餐厅",
      keyframe: "kitchen_frame_4.jpg",
    },
  ],
  validations: [
    { status: "pass", text: "所有提示词包含明确主体描述" },
    { status: "pass", text: "无抽象描述、无古诗词" },
    { status: "pass", text: "每段对应3秒片段，动作精简" },
    { status: "warn", text: "分镜#3含2次焦点转移（建议减至1次）" },
    { status: "pass", text: "跨分镜风格一致（人种/色调/光影统一）" },
  ],
  videoType: "美食类",
};

export const mockTemplates: Template[] = [
  {
    id: "t1",
    type: "口播类",
    name: "口播人物+背景",
    description: "人物外观+手势动作+表情变化+背景场景，适合口播/讲解类视频",
    preview: "一位{外观}的{人种}{性别}坐在{背景}，{手势动作}，{表情}，{光影}",
    saved: false,
  },
  {
    id: "t2",
    type: "美食类",
    name: "美食烹饪过程",
    description: "食材外观+烹饪动作+翻拌细节+烟火光影，适合美食教程/展示",
    preview: "{食材外观}在{厨具}中{烹饪动作}，{烟火光影}，暖色调侧光",
    saved: false,
  },
  {
    id: "t3",
    type: "电商类",
    name: "产品展示+使用",
    description: "主体+产品外观+使用动作+光影质感，适合产品展示/带货视频",
    preview: "一位{外观}的{人种}{性别}{使用动作}{产品}，{光影质感}，{色调}",
    saved: true,
  },
  {
    id: "t4",
    type: "短剧类",
    name: "人物对话+情绪",
    description: "人物外观+表情动作+对话场景+情绪转折+景别变化",
    preview: "{人物外观}在{场景}中{表情动作}，{情绪转折}，{景别变化}",
    saved: false,
  },
  {
    id: "t5",
    type: "仙侠类",
    name: "仙侠特效+场景",
    description: "服饰细节+法术动作+环境特效+冷色调风格",
    preview: "一位穿{服饰}的{角色}在{环境}中{法术动作}，{特效}，冷色调逆光",
    saved: false,
  },
  {
    id: "t6",
    type: "通用",
    name: "基础公式模板",
    description: "即梦基础公式：主体+外观+运动，适合简单场景",
    preview: "【{主体}】+【{外观描述}】+【{运动}】，【{风格词}】",
    saved: false,
  },
];

export const mockHistory: HistoryItem[] = [
  {
    id: "h1",
    title: "美食教程-你还在这样炒菜吗",
    date: "2026-05-27 14:30",
    shotsCount: 4,
    hooksCount: 3,
    strategy: "美食类策略",
    tags: ["美食类", "文生+图生", "已导出"],
  },
  {
    id: "h2",
    title: "健身教练-30天腹肌挑战",
    date: "2026-05-26 09:15",
    shotsCount: 4,
    hooksCount: 2,
    strategy: "口播类策略",
    tags: ["口播类", "文生"],
  },
  {
    id: "h3",
    title: "美妆博主-夏日防晒测评",
    date: "2026-05-25 16:45",
    shotsCount: 6,
    hooksCount: 4,
    strategy: "电商类策略",
    tags: ["电商类", "文生+图生"],
  },
];